---
apiVersion: v1
kind: ReplicationController
metadata:
  name: insult
spec:
  replicas: 3
  selector:
    app: insult
  template:
    metadata:
      labels:
        app: insult
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: us.gcr.io/hackathon-179114/ingress:0.1
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: http_proxy
          value: $(NODE_NAME):4140
        ports:
        - name: service
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: insult
spec:
  selector:
    app: insult
  clusterIP: None
  ports:
  - name: http
    port: 8080