---
apiVersion: v1
kind: ReplicationController
metadata:
  name: insult-now
spec:
  replicas: 3
  selector:
    app: insult-now
  template:
    metadata:
      labels:
        app: insult-now
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: us.gcr.io/hackathon-179114/aggregator:0.1.0
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: http_proxy
          value: $(NODE_NAME):4140
        ports:
        - name: service
          containerPort: 7998
---
apiVersion: v1
kind: Service
metadata:
  name: insult-now
spec:
  selector:
    app: insult-now
  clusterIP: None
  ports:
  - name: http
    port: 7998
---

apiVersion: v1
kind: ReplicationController
metadata:
  name: insult-rude
spec:
  replicas: 3
  selector:
    app: insult-rude
  template:
    metadata:
      labels:
        app: insult-rude
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: us.gcr.io/hackathon-179114/ingress:0.1.0
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: http_proxy
          value: $(NODE_NAME):4140
        ports:
        - name: service
          containerPort: 7999
---
apiVersion: v1
kind: Service
metadata:
  name: insult-rude
spec:
  selector:
    app: insult-rude
  clusterIP: None
  ports:
  - name: http
    port: 7999